openapi: 3.0.0
info:
  title: test
  version: 1.0.0
paths:
  /department:
    post:
      pathType: default
      serviceProvider: ''
      cron: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dept_name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '402':
          description: Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    get:
      pathType: default
      serviceProvider: ''
      cron: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  dept_id:
                    type: integer
                  dept_name:
                    type: string
        '402':
          description: Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
  /department/{id}:
    get:
      pathType: default
      serviceProvider: ''
      cron: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  dept_id:
                    type: integer
                  dept_name:
                    type: string
                  location:
                    type: string
        '402':
          description: Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    delete:
      pathType: default
      serviceProvider: ''
      cron: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '402':
          description: Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    put:
      pathType: default
      serviceProvider: ''
      cron: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dept_name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '402':
          description: Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
